Hairy Messy Ugly shell script to emulate xxd
On client machines where there is no `xxd` binary present, but we do
find `bc` we can now properly un-hexdump the files being sent by the
server.  It's crazy slow for large files but it works well enough.

I also changed the way the push process works, removing the hexdump
transformation when initially sending across the netskel client itself,
instead receiving it via a 'rawclient' server method.  This isn't
awesome, but it's safe enough for a first push and if it fails nothing
automated will be broken.

Resolves #5

diff --git a/client/netskel b/client/netskel
--- a/client/netskel
+++ b/client/netskel
@@ -113,6 +113,8 @@ netskel_preflight() {
   netskel_find_executable md5
   netskel_find_executable md5sum
   netskel_find_executable ssh
+  netskel_find_executable xxd
+  netskel_find_executable bc
 
   if [ -x $HOME/bin/pre-netskel ] ; then
     $HOME/bin/pre-netskel
@@ -145,10 +147,26 @@ netskel_cleanup() {
 netskel_fetch_file() {
   NETSKEL_TARGET=$NETSKEL_TMP/`basename $1`
 
-  $SSH sendfile db/$1 $NETSKEL_UUID $USERNAME $HOSTNAME > $NETSKEL_TMP/xxdfile && xxd -p -r $NETSKEL_TMP/xxdfile > $NETSKEL_TARGET
-  RETVAL=$?
+  $SSH sendfile db/$1 $NETSKEL_UUID $USERNAME $HOSTNAME > $NETSKEL_TMP/xxdfile
 
-  rm -f $NETSKEL_TMP/xxdfile
+  if [ "$NETSKEL_PATH_xxd" != "" ] ; then
+    xxd -p -r $NETSKEL_TMP/xxdfile > $NETSKEL_TARGET
+    RETVAL=$?
+    netskel_trace "Processed $NETSKEL_TARGET via xxd ($RETVAL)"
+  else
+    if [ "$NETSKEL_PATH_bc" = "" ] ; then
+        echo 'This host needs either xxd or bc installed to be able to process'
+        echo 'the Netskel hexdump file transfers.  Sorry'
+        exit 1
+    fi
+    # This mess will do the work of xxd (tested on FreeBSD only)
+    echo 'ibase=16; obase=8' > $NETSKEL_TMP/bcfile
+    cat $NETSKEL_TMP/xxdfile | sed -e 's/\(..\)/\1;/g' | tr 'a-z' 'A-Z' >> $NETSKEL_TMP/bcfile
+    cat $NETSKEL_TMP/bcfile | bc | sed -e 's/^/\\\\\\/g' | xargs -n 1 printf > $NETSKEL_TARGET
+    RETVAL=$?
+    netskel_trace "Processed $NETSKEL_TARGET via sed|tr|bc|sed|xargs|printf ($RETVAL)"
+  fi
+  rm -f $NETSKEL_TMP/xxdfile $NETSKEL_TMP/bcfile
 
   return $RETVAL
 }
@@ -248,7 +266,7 @@ fi
 case $1 in
   sync)
     # Grab latest netskeldb
-	$SSH netskeldb $NETSKEL_UUID $USERNAME $HOSTNAME > $NETSKEL_TMP/.netskeldb && mv $NETSKEL_TMP/.netskeldb $NETSKEL_DBFILE || netskel_die "Unable to fetch dbfile"
+    $SSH netskeldb $NETSKEL_UUID $USERNAME $HOSTNAME > $NETSKEL_TMP/.netskeldb && mv $NETSKEL_TMP/.netskeldb $NETSKEL_DBFILE || netskel_die "Unable to fetch dbfile"
 
     # Check all the files in db, see if they need synching
     for file in `grep -v "#" $NETSKEL_DBFILE | cut -f 1 | xargs`; do
@@ -275,28 +293,28 @@ case $1 in
     if [ -r $NETSKEL_IDENTITY ] ; then
       echo "ERROR: $NETSKEL_IDENTITY already exists"
       echo "       Please remove this file if you want to re-init"
-	  echo " "
-	  ls -la $NETSKEL_IDENTITY
-	  echo " "
+      echo " "
+      ls -la $NETSKEL_IDENTITY
+      echo " "
       exit 1
     fi
 
-	$SSH addkey $USERNAME $HOSTNAME > $NETSKEL_IDENTITY
+    $SSH addkey $USERNAME $HOSTNAME > $NETSKEL_IDENTITY
     chmod 400 $NETSKEL_IDENTITY
     NETSKEL_UUID=`grep "CLIENT_UUID" $HOME/.netskel/identity | tr -s ' ' | cut -d ' ' -f 3`
 
     if [ "$NETSKEL_UUID" = "" ] ; then
-		echo "ERROR: Failed to receive Client ID and Private Key from Netskel Server"
-		echo " "
-		ls -la $NETSKEL_IDENTITY
-		echo " "
-		rm -f $NETSKEL_IDENTITY
-		exit 1
-	fi
+        echo "ERROR: Failed to receive Client ID and Private Key from Netskel Server"
+        echo " "
+        ls -la $NETSKEL_IDENTITY
+        echo " "
+        rm -f $NETSKEL_IDENTITY
+        exit 1
+    fi
 
-	echo " "
-	echo "The Netskel server assigned client ID: $NETSKEL_UUID"
-	echo " "
+    echo " "
+    echo "The Netskel server assigned client ID: $NETSKEL_UUID"
+    echo " "
 
     netskel_cleanup
     exit 0
@@ -305,33 +323,29 @@ case $1 in
   push)
     NETSKEL_INSTALL_SCRIPT=$NETSKEL_TMP/install.sh
 
-	netskel_log "Bundling a Netskel Install Pack for $1"
+    netskel_log "Bundling a Netskel Install Pack for $1"
 
     echo 'echo "Running Netskel Install Pack on `hostname`"' > $NETSKEL_INSTALL_SCRIPT
     echo 'test -d $HOME/bin || mkdir $HOME/bin' >> $NETSKEL_INSTALL_SCRIPT
+    echo 'test -d $HOME/.netskel || mkdir $HOME/.netskel' >> $NETSKEL_INSTALL_SCRIPT
+    echo 'chmod 700 $HOME/bin $HOME/.netskel' >> $NETSKEL_INSTALL_SCRIPT
 
-    echo 'cat > netskel.xxdp << EOF' >> $NETSKEL_INSTALL_SCRIPT
-    xxd -p $0 >> $NETSKEL_INSTALL_SCRIPT
+    echo 'cat > $HOME/.netskel/config << EOF' >> $NETSKEL_INSTALL_SCRIPT
+    cat $HOME/.netskel/config >> $NETSKEL_INSTALL_SCRIPT
     echo 'EOF' >> $NETSKEL_INSTALL_SCRIPT
-    echo 'xxd -p -r netskel.xxdp > $HOME/bin/netskel' >> $NETSKEL_INSTALL_SCRIPT
-    echo 'rm netskel.xxdp' >> $NETSKEL_INSTALL_SCRIPT
-    echo 'chmod 755 $HOME/bin/netskel' >> $NETSKEL_INSTALL_SCRIPT
-
-    echo 'cat > netskelrc.xxdp << EOF' >> $NETSKEL_INSTALL_SCRIPT
-    xxd -p $HOME/.netskel/config >> $NETSKEL_INSTALL_SCRIPT
-    echo 'EOF' >> $NETSKEL_INSTALL_SCRIPT
-    echo 'xxd -p -r netskelrc.xxdp > $HOME/.netskel/config' >> $NETSKEL_INSTALL_SCRIPT
-    echo 'rm netskelrc.xxdp' >> $NETSKEL_INSTALL_SCRIPT
     echo 'chmod 600 $HOME/.netskel/config' >> $NETSKEL_INSTALL_SCRIPT
+
+    echo "ssh -p $NETSKEL_PORT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $NETSKEL_SERVER rawclient > ./bin/netskel" >> $NETSKEL_INSTALL_SCRIPT
+    echo 'chmod 700 $HOME/bin/netskel' >> $NETSKEL_INSTALL_SCRIPT
 
     echo '$HOME/bin/netskel init && \' >> $NETSKEL_INSTALL_SCRIPT
     echo 'echo "Syncing this host for the first time:" && \' >> $NETSKEL_INSTALL_SCRIPT
-	echo '$HOME/bin/netskel sync' >> $NETSKEL_INSTALL_SCRIPT
+    echo '$HOME/bin/netskel sync' >> $NETSKEL_INSTALL_SCRIPT
 
     netskel_log "Pushing Pack:"
-	echo "-- "
+    echo "-- "
     ssh -ATq -o ConnectTimeout=5 $2 /bin/sh < $NETSKEL_INSTALL_SCRIPT || netskel_log "Unable to connect to $2"
-	echo "-- "
+    echo "-- "
 
     netskel_cleanup
     exit 0
