Use basename on -bash

diff --git a/client/netskel b/client/netskel
--- a/client/netskel
+++ b/client/netskel
@@ -351,7 +351,7 @@ case $1 in
   ;;
 
   *)
-  echo "$0: invalid argument -- $1" >&2
+  echo "`basename $0`: invalid argument -- $1" >&2
   usage
   ;;
 esac
